
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tpuv6-zeronas-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tpuv6-zeronas
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
